setup readme
zachar-chorny/taxi-service pull request #1
Opened 2021-12-14 18:37 UTC by zachar-chorny

2021-12-14 21:06 UTC, Panchenko-Volodymyr approved these changes

2021-12-15 10:31 UTC, Nick97-git requested changes
- Remove redundant / from endpoints like /cars/, /drivers/ and /manufacturers/ from all places where you use them
- at the moment your path looks like src/main/java/mate... We should rename "mate" to something else, like "taxi". After you do that don't forget to change the value you pass to the Injector.getInstance() everywhere you use it
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns
- remove empty line in `doFilter()` method)

2021-12-15 10:31 UTC, Nick97-git commented on README.md
> +#### Web technologies:
let's unite them

2021-12-15 13:11 UTC, Nick97-git approved these changes

2021-12-15 13:24 UTC, merged